# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63b050aa0e29a5813c0831536335f1c2b1dfe5ae6a1c5b4ffa07b88805d06052400e531e8d65d1906da390caa8601a83e9f2bbdb150a995be1ea03e46077c65

test:
  secret_key_base: 2e243823ff66758bb01af55529075d89b352871cfaf3746362be92f9a900540e55fe4b84f312ead4e353404eb1c6abe6e28dd4b52ac87fd2cca8d25b930575bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
